# Generated by Django 3.1.1 on 2020-09-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Food',
        ),
    ]
